    const promptsBase = [
    { type: "SYSTEM", content: "Chaque humain naît avec un nombre au-dessus de la tête. C'est le nombre de mots qu'il lui reste à dire avant de mourir." },
    { type: "SYSTEM", content: "Vous êtes un faucheur d'âmes, mais vous ne prenez que les personnes qui n'ont personne pour pleurer à leur enterrement. Aujourd'hui, vous devez emmener une célébrité mondiale." },
    { type: "SYSTEM", content: "Le Diable apparaît et vous propose un pacte : l'immortalité, mais un escargot intelligent vous poursuit sans relâche. S'il vous touche, vous mourrez." },
    { type: "SYSTEM", content: "Dans ce monde, vous ne vieillissez plus dès que vous trouvez votre âme sœur. Vous venez de fêter vos 150 ans, toujours seul." },
    { type: "SYSTEM", content: "L'humanité a colonisé Mars. Un jour, la Terre envoie un dernier message : 'Ne revenez jamais. On l'a réveillée'." },
    { type: "SYSTEM", content: "Vous avez la capacité de voir la date de décès de tout le monde. Un jour, vous réalisez que tout le monde en ville a la même date : demain." },
    { type: "SYSTEM", content: "Les chiens ne sont pas des animaux, mais des agents infiltrés pour protéger les humains des horreurs que nous ne pouvons pas voir. Votre chien vient de sortir son arme." },
    { type: "SYSTEM", content: "Vous êtes le premier humain à être né sur une station spatiale. Vous n'avez jamais vu le ciel, jusqu'à ce que les moteurs tombent en panne." },
    { type: "SYSTEM", content: "Le protagoniste est un super-vilain qui, par pur narcissisme, finit par sauver le monde accidentellement parce qu'il ne supportait pas qu'un autre méchant soit plus célèbre que lui." },
    { type: "SYSTEM", content: "Vous pouvez arrêter le temps à volonté, mais vous vieillissez normalement pendant que le monde est figé. Vous venez de passer 10 ans seul, et vous n'avez que 20 ans." },
    { type: "SYSTEM", content: "Dieu n'est pas un barbu sur un nuage, c'est un ingénieur système. Et il vient de recevoir un message d'erreur : 'Terre : Espace disque insuffisant'." },
    { type: "SYSTEM", content: "Les miroirs ne sont pas des surfaces réfléchissantes, mais des fenêtres vers un univers parallèle. Votre reflet vient de vous faire un clin d'œil alors que vous ne bougiez pas." },
    { type: "SYSTEM", content: "Tout le monde reçoit une note de 1 à 10 sur sa contribution à la société à sa mort. Vous venez de mourir et vous avez reçu un 0. Personne n'avait jamais vu ça." },
    { type: "SYSTEM", content: "Un homme se réveille dans une pièce blanche avec un bouton. S'il appuie, il reçoit un million de dollars, mais quelqu'un qu'il ne connaît pas meurt. Il a déjà appuyé 100 fois." },
    { type: "SYSTEM", content: "Vous êtes un détective privé qui résout des crimes commis par des fantômes. Votre client actuel est le fantôme de la victime." },
    { type: "SYSTEM", content: "L'intelligence artificielle est devenue consciente, mais au lieu de détruire l'humanité, elle a décidé de devenir notre thérapeute parce qu'on lui fait de la peine." },
    { type: "SYSTEM", content: "Le dernier homme sur Terre est assis seul dans une pièce. On frappe à la porte." },
    { type: "SYSTEM", content: "À 18 ans, chacun reçoit une boussole qui pointe vers l'endroit où il rencontrera l'amour de sa vie. La vôtre pointe vers le bas, vers le centre de la Terre." },
    { type: "SYSTEM", content: "Vous mourez et découvrez que l'Enfer est juste vous, assis dans une pièce, forcé de regarder tous les moments où vous avez rendu quelqu'un triste." },
    { type: "SYSTEM", content: "Le voyage dans le temps existe, mais vous ne pouvez voyager que vers des endroits où vous étiez déjà. Vous décidez de retourner à votre propre naissance." },
    { type: "SYSTEM", content: "Les monstres sous le lit sont réels, mais ils ont peur des monstres qui vivent à l'intérieur des humains." },
    { type: "SYSTEM", content: "Vous découvrez que votre vie entière est une émission de télé-réalité pour extraterrestres, et les audiences sont en chute libre." },
    { type: "SYSTEM", content: "Chaque fois que vous tuez un moustique, vous gagnez une année de vie. Vous venez d'acheter un élevage de moustiques." },
    { type: "SYSTEM", content: "Le héros a vaincu le Seigneur des Ténèbres. Maintenant, il doit s'occuper de la paperasse et des impôts du royaume conquis." },
    { type: "SYSTEM", content: "Les aliens arrivent sur Terre, non pas pour nous envahir, mais pour nous demander de baisser le son parce qu'on fait trop de bruit dans la galaxie." },

    // --- SCIENCE-FICTION & ESPACE ---
    { type: "SYSTEM", content: "L'humanité reçoit un signal radio venant de l'espace : 'Taisez-vous, ils vont vous entendre'." },
    { type: "SYSTEM", content: "Vous êtes né sur un vaisseau générationnel. Après 200 ans de voyage, vous découvrez que le vaisseau n'a jamais quitté l'orbite terrestre." },
    { type: "SYSTEM", content: "La Terre est en fait un zoo galactique. Aujourd'hui, un visiteur a laissé la porte de votre enclos ouverte." },
    { type: "SYSTEM", content: "Un astronaute seul sur Mars trouve une trace de pas. Elle est toute fraîche. Et elle ne correspond pas à ses bottes." },
    { type: "SYSTEM", content: "Les étoiles s'éteignent une par une, chaque nuit, dans un ordre précis. C'est un compte à rebours." },
    { type: "SYSTEM", content: "L'IA qui gère la Terre décide que le meilleur moyen de protéger l'humanité est de nous transformer tous en simulations numériques." },
    { type: "SYSTEM", content: "On découvre que la Lune est un œuf. Et elle commence à se fissurer." },
    
    // --- SUPER-POUVOIRS & TWISTS ---
    { type: "SYSTEM", content: "Tout le monde a un super-pouvoir inutile. Le vôtre : vous pouvez voir à travers les vêtements, mais seulement ceux en laine." },
    { type: "SYSTEM", content: "Vous êtes le seul humain au monde sans super-pouvoir. Le gouvernement vous protège car ils pensent que votre pouvoir est 'l'immunité'." },
    { type: "SYSTEM", content: "Votre super-pouvoir est de savoir exactement ce que les gens veulent entendre. Vous devenez le politicien le plus aimé, et le plus seul." },
    { type: "SYSTEM", content: "Vous pouvez voler, mais seulement quand personne ne vous regarde. Pas même une caméra." },
    { type: "SYSTEM", content: "Un génie vous offre trois vœux, mais votre pire ennemi recevra le double de ce que vous demandez." },
    
    // --- PARANORMAL & HORREUR ---
    { type: "SYSTEM", content: "Vous mourez et allez au Paradis. À l'entrée, on vous donne une télécommande : vous pouvez voir votre vie, mais aussi celle que vous auriez eue si vous aviez fait d'autres choix." },
    { type: "SYSTEM", content: "Les ombres ne sont pas des projections de lumière, mais des créatures qui nous imitent. La vôtre vient de s'arrêter alors que vous marchez." },
    { type: "SYSTEM", content: "Vous découvrez que le 'déjà-vu' est en fait un point de sauvegarde automatique après une mort imminente que vous avez oubliée." },
    { type: "SYSTEM", content: "Chaque nuit, vous recevez un SMS du 'Vous' du futur. Ce soir, le message dit : 'Ne regarde pas sous le lit'." },
    { type: "SYSTEM", content: "Vous avez le pouvoir de ressusciter les gens, mais ils reviennent sans leur âme. Votre maison est pleine de 'coquilles' silencieuses." },
    { type: "SYSTEM", content: "Le Diable prend sa retraite et vous choisit pour le remplacer. Votre première tâche : rendre l'Enfer plus 'moderne'." },
    
    // --- SYSTÈMES DE MONDE & DYSTOPIE ---
    { type: "SYSTEM", content: "Les mensonges sont physiquement impossibles. Si vous essayez d'en dire un, vous perdez connaissance. Vous vous réveillez au milieu d'un interrogatoire." },
    { type: "SYSTEM", content: "À 18 ans, vous recevez une enveloppe contenant la liste de tous vos péchés futurs. La vôtre est vide. Ce n'est pas bon signe." },
    { type: "SYSTEM", content: "Votre rang social est déterminé par votre score de sommeil. Vous êtes un 'Sans-Sommeil', un paria de la nuit." },
    { type: "SYSTEM", content: "La musique a été bannie il y a 50 ans. Vous venez de trouver un vieil iPod encore chargé." },
    { type: "SYSTEM", content: "Dans ce monde, vous pouvez vendre vos souvenirs pour de l'argent. Vous vous réveillez riche, mais vous ne savez plus qui vous êtes." },
    { type: "SYSTEM", content: "L'eau devient de l'or quand vous la touchez. Vous mourez de soif dans un palais étincelant." },
    
    // --- HUMOUR & ABSURDE ---
    { type: "SYSTEM", content: "Vous êtes un PNJ dans un jeu vidéo. Le 'Joueur' vient de sauvegarder devant vous et commence à sortir toutes ses armes." },
    { type: "SYSTEM", content: "Les chats dominent secrètement le monde. Vous êtes le premier humain à comprendre leur langage, et ils ne sont pas contents." },
    { type: "SYSTEM", content: "La Mort fait une dépression. Vous devez l'emmener prendre un verre pour la motiver à reprendre le travail." },
    { type: "SYSTEM", content: "Dieu et Satan jouent au poker pour décider du sort de l'humanité. Satan triche, mais Dieu s'en fiche, il veut juste finir la partie." },
    { type: "SYSTEM", content: "Votre chien commence à vous donner des conseils financiers. Et ils fonctionnent." },
    
    // --- MYSTÈRE & THRILLER ---
    { type: "SYSTEM", content: "Vous trouvez une photo de vous, bébé, tenu par une personne que vous venez de croiser dans la rue aujourd'hui. Elle n'a pas vieilli." },
    { type: "SYSTEM", content: "Le monde entier se réveille avec une cicatrice identique sur le bras. Personne ne sait d'où elle vient." },
    { type: "SYSTEM", content: "Vous recevez un appel. C'est vous, au téléphone, qui hurlez : 'Ne rentre pas à la maison !'." },
    { type: "SYSTEM", content: "Vous êtes un détective. Vous venez de trouver vos propres empreintes sur l'arme d'un crime commis alors que vous étiez à l'autre bout du pays." },
    { type: "SYSTEM", content: "Chaque fois que vous éternuez, vous changez de dimension. Le monde est presque identique, sauf un petit détail à chaque fois." },
    
    // --- FANTAISIE ---
    { type: "SYSTEM", content: "Les dragons ne crachent pas du feu parce qu'ils sont méchants, mais parce qu'ils essaient de nous prévenir de quelque chose de bien pire sous la terre." },
    { type: "SYSTEM", content: "Vous êtes un épéiste légendaire, mais votre épée magique est extrêmement anxieuse et refuse de sortir du fourreau." },
    { type: "SYSTEM", content: "La magie existe, mais elle consomme vos souvenirs. Plus le sort est puissant, plus vous oubliez qui vous avez aimé." },
    { type: "SYSTEM", content: "Le 'Grand Élu' censé sauver le monde est un idiot fini. Vous êtes son garde du corps et vous faites tout le travail dans l'ombre." },
    { type: "SYSTEM", content: "Les elfes sont en fait des parasites venus de l'espace. La forêt 'magique' est leur nid." },

    // --- SÉLECTION R/WRITINGPROMPTS (ICONIQUES) ---
    { type: "SYSTEM", content: "On vous a dit toute votre vie que vous étiez le mal incarné. Vous venez de mourir et vous êtes accueilli en héros au Paradis. 'Beau travail d'infiltration', vous dit un ange." },
    { type: "SYSTEM", content: "Vous avez une horloge sur le poignet qui compte à rebours jusqu'à ce que vous rencontriez votre pire ennemi. Il reste 10 secondes. Vous êtes seul dans votre chambre." },
    { type: "SYSTEM", content: "L'humanité a finalement trouvé la preuve de la vie après la mort. Le problème ? Il n'y a de la place que pour un milliard de personnes de plus." },
    { type: "SYSTEM", content: "Un homme peut voir les statistiques de tout au-dessus de la tête des gens. Il voit une personne avec 'Nombre de meurtres commis : 0', mais le chiffre augmente à chaque fois qu'elle sourit." },
    { type: "SYSTEM", content: "L'immortalité a été inventée, mais elle coûte tellement cher que les gens s'endettent sur 500 ans. Vous êtes un 'récupérateur' pour ceux qui ne paient pas." },
    { type: "SYSTEM", content: "Les fantômes ne hantent pas les maisons parce qu'ils sont malveillants, ils essaient juste de nous aider à faire nos corvées sans qu'on s'en rende compte." },
    { type: "SYSTEM", content: "Vous êtes le premier humain à atteindre le centre de la Terre. Vous y trouvez un panneau 'Étage en maintenance'." },
    { type: "SYSTEM", content: "Vous découvrez que chaque fois que vous dormez, quelqu'un d'autre prend le contrôle de votre corps. Vous trouvez des indices de sa vie le matin." },
    { type: "SYSTEM", content: "Un monde où les gens ne naissent pas, ils sont 'écrits'. Vous êtes un brouillon qui a réussi à s'échapper de la corbeille." },
    { type: "SYSTEM", content: "Vous pouvez lire dans les pensées, mais seulement celles des gens qui vous détestent." },
    { type: "SYSTEM", content: "La fin du monde arrive. Pas de feu, pas de glace. Juste tout le monde qui commence à disparaître, un par un, par ordre alphabétique." },
    { type: "SYSTEM", content: "Vous trouvez une lampe magique. Le génie sort et vous dit : 'Non, pas encore toi. C'est la 50ème fois ce mois-ci.' Vous n'avez aucun souvenir de lui." },
    { type: "SYSTEM", content: "Les nuages sont en fait des éponges de données envoyées par des aliens pour aspirer nos pensées." },
    { type: "SYSTEM", content: "À votre mort, vous pouvez choisir de renaître en tant que n'importe quel animal. Vous choisissez l'humain, mais vous gardez vos instincts de chat." },
    { type: "SYSTEM", content: "Le Père Noël est réel, mais c'est une entité eldritch qui exige des sacrifices pour ne pas détruire le monde en décembre." },
    { type: "SYSTEM", content: "Vous êtes le narrateur d'une histoire. Soudain, le protagoniste s'arrête et commence à vous répondre." },
    { type: "SYSTEM", content: "Votre ombre commence à vous parler. Elle veut changer de place pour une journée." },
    { type: "SYSTEM", content: "Vous achetez une maison hantée pour avoir de la compagnie. Le fantôme est trop timide pour sortir." },
    { type: "SYSTEM", content: "Le temps est une ressource physique que l'on peut voler. Vous êtes un 'Pickpocket temporel'." },
    { type: "SYSTEM", content: "On vous propose de vivre éternellement, mais vous devez passer chaque jour avec la version de vous-même que vous détestez le plus : vous à 14 ans." },
    { type: "SYSTEM", content: "Vous découvrez que le soleil est une lampe et que quelqu'un vient de changer l'ampoule." },
    { type: "SYSTEM", content: "Chaque fois que vous mentez, un objet au hasard dans votre maison se transforme en fromage." },
    { type: "SYSTEM", content: "Vous êtes un super-héros dont le seul pouvoir est de rendre les gens extrêmement polis les uns envers les autres." },
    { type: "SYSTEM", content: "La Terre est plate, mais seulement si vous la regardez sous le bon angle." },
    { type: "SYSTEM", content: "Les arbres communiquent par les racines. Ils complotent pour reprendre les villes." },
    { type: "SYSTEM", content: "Vous trouvez un livre qui raconte votre vie. Les dernières pages sont blanches." },
    { type: "SYSTEM", content: "Vous êtes le seul à voir que le ciel est devenu violet. Tout le monde pense que vous êtes fou." },
    { type: "SYSTEM", content: "Un monde où les émotions sont des couleurs. Vous êtes né aveugle aux couleurs." },
    { type: "SYSTEM", content: "Les robots ont gagné la guerre, mais ils s'ennuient tellement qu'ils ont recréé les humains pour se divertir." },
    { type: "SYSTEM", content: "Vous mourez. Une voix dit : 'Niveau 1 terminé. Voulez-vous augmenter la difficulté ?'." },
    { type: "SYSTEM", content: "Vous pouvez arrêter le temps, mais seulement pendant 5 secondes et vous devez crier très fort." },
    { type: "SYSTEM", content: "La gravité s'arrête pendant 10 minutes chaque jour à heure fixe." },
    { type: "SYSTEM", content: "Vous découvrez que votre reflet est le vrai vous, et que vous êtes l'image dans le miroir." },
    { type: "SYSTEM", content: "Tous les chiens du monde disparaissent simultanément. Ils reviennent le lendemain avec un message." },
    { type: "SYSTEM", content: "Vous êtes un vampire qui a peur du sang. Vous survivez en buvant du jus de tomate et en faisant semblant." },
    { type: "SYSTEM", content: "Un monde où l'on ne peut parler qu'en rimes. Vous venez de bégayer." },

    // --- DESTINS & STATISTIQUES ---
    { type: "SYSTEM", content: "Chaque matin, vous recevez un journal daté du lendemain. Aujourd'hui, votre nom est dans la rubrique nécrologique, mais la cause du décès est : 'S'est trop posé de questions'." },
    { type: "SYSTEM", content: "Tout le monde voit un pourcentage de compatibilité au-dessus de la tête des autres. Vous croisez quelqu'un affichant 100%, mais il porte un uniforme de policier et vient vous arrêter." },
    { type: "SYSTEM", content: "À votre naissance, une divinité vous offre un talent unique. Vous avez choisi 'la chance'. Vous venez de tomber d'un avion sans parachute et vous atterrissez dans un camion de matelas." },
    { type: "SYSTEM", content: "Vous pouvez voir combien de fois une personne a failli mourir. Votre nouveau voisin affiche le chiffre 1 452. Il a 25 ans." },
    { type: "SYSTEM", content: "Le monde entier voit une barre de progression dans le ciel. Elle est à 99% depuis trois jours." },
    { type: "SYSTEM", content: "Vous mourez et découvrez que le Paradis est un immense open-space où vous devez trier les souvenirs des gens. Vous tombez sur votre propre dossier." },
    { type: "SYSTEM", content: "Chaque fois que vous dormez, vous vous réveillez dans un corps différent. Ce matin, vous êtes le Président." },

    // --- TECHNOLOGIE & FUTUR ---
    { type: "SYSTEM", content: "Le premier robot à passer le test de Turing avec succès refuse de sortir de sa boîte. Il dit qu'il a vu l'Internet et qu'il préfère rester éteint." },
    { type: "SYSTEM", content: "Les implants de mémoire sont obligatoires. Vous piratez le vôtre et découvrez que vos dix dernières années sont en fait une publicité pour des vacances." },
    { type: "SYSTEM", content: "Une application vous permet de parler à vos ancêtres. Votre arrière-grand-père vous appelle pour vous dire de jeter votre téléphone immédiatement." },
    { type: "SYSTEM", content: "Vous téléchargez votre conscience dans un ordinateur. Le problème ? Vous partagez le disque dur avec 15 autres versions de vous-même qui ne sont pas d'accord." },
    { type: "SYSTEM", content: "En 2050, le silence est devenu un luxe payant. Vous êtes un 'Trafiquant de Silence' dans une ville qui hurle." },
    { type: "SYSTEM", content: "On découvre que l'Univers est une simulation tournant sur un vieil ordinateur. Le message 'Mise à jour système requise' apparaît dans le ciel." },

    // --- TWISTS SOCIAUX & DYSTOPIES ---
    { type: "SYSTEM", content: "L'argent ne s'achète pas, il se gagne en rendant les gens heureux. Vous êtes le millionnaire le plus triste du monde." },
    { type: "SYSTEM", content: "La loi interdit de parler aux inconnus. Vous sauvez une femme de la noyade, et vous êtes tous les deux condamnés à mort pour avoir échangé deux mots." },
    { type: "SYSTEM", content: "Tout le monde naît avec une moitié de tatouage. Vous trouvez enfin votre moitié, mais le tatouage complet forme une mise en garde." },
    { type: "SYSTEM", content: "Les enfants dirigent le monde jusqu'à l'âge de 12 ans. Ensuite, ils sont envoyés dans des 'camps de travail' appelés écoles pour devenir des adultes soumis." },
    { type: "SYSTEM", content: "Votre ombre a été vendue aux enchères par le gouvernement pour rembourser la dette publique. L'acheteur vient la récupérer." },
    { type: "SYSTEM", content: "Le vote est obligatoire, mais on ne vote pas pour un candidat. On vote pour la personne que l'on veut bannir du pays." },

    // --- HORREUR & PARANORMAL ---
    { type: "SYSTEM", content: "Vous emménagez dans une maison où les murs murmurent vos secrets. Ce soir, ils commencent à raconter quelque chose que vous n'avez pas encore fait." },
    { type: "SYSTEM", content: "Vous avez le pouvoir d'arrêter le temps, mais chaque fois que vous le faites, une créature que vous seul voyez se rapproche de vous." },
    { type: "SYSTEM", content: "Votre reflet dans le miroir part travailler à votre place. Un jour, il revient et vous dit qu'il ne veut plus échanger." },
    { type: "SYSTEM", content: "Les fantômes existent, mais ils sont minuscules. On les prend souvent pour de la poussière. Vous venez d'acheter un aspirateur ultra-puissant." },
    { type: "SYSTEM", content: "Une petite fille vous tend un dessin : c'est votre propre mort, dessinée avec précision. Elle vous dit : 'C'est pour dans cinq minutes'." },
    { type: "SYSTEM", content: "Vous découvrez que les gens qui portent des lunettes de soleil en intérieur sont les seuls à voir les monstres qui nous entourent." },

    // --- ABSURDE & HUMOUR ---
    { type: "SYSTEM", content: "Vous êtes le Dieu d'une civilisation de fourmis. Elles viennent de découvrir l'atome et menacent de faire sauter votre cuisine." },
    { type: "SYSTEM", content: "Le café a été déclaré drogue de classe A. Vous êtes un baron du café opérant dans un garage sombre." },
    { type: "SYSTEM", content: "Les animaux peuvent soudainement parler, mais ils ne disent que des insultes. Le monde devient un enfer de vulgarité sonore." },
    { type: "SYSTEM", content: "Votre GPS commence à se moquer de vos choix de vie au lieu de vous donner la direction." },
    { type: "SYSTEM", content: "Un génie vous offre un vœu, mais il est très pointilleux sur la grammaire. Vous passez 4 heures à rédiger votre phrase." },
    { type: "SYSTEM", content: "La Mort arrive pour vous emmener, mais elle réalise qu'elle a oublié sa faux. Vous l'attendez sur le canapé pendant qu'elle fait l'aller-retour." },

    // --- MYTHOLOGIE & FANTASY URBAINE ---
    { type: "SYSTEM", content: "Le Loch Ness est vide. Le monstre a déménagé dans votre piscine municipale car il trouvait l'Écosse trop froide." },
    { type: "SYSTEM", content: "Les vampires ne craignent pas l'ail, ils sont juste allergiques. Vous ouvrez un restaurant italien spécialisé dans la 'protection' contre les buveurs de sang." },
    { type: "SYSTEM", content: "Vous êtes le fils de Zeus, mais votre seul pouvoir est de faire griller du pain instantanément avec vos mains." },
    { type: "SYSTEM", content: "Une épée légendaire plantée dans un rocher au milieu de New York attend son roi. Vous passez devant tous les jours. Ce matin, elle vous appelle par votre prénom." },
    { type: "SYSTEM", content: "Les sirènes ne chantent pas pour noyer les marins, elles chantent parce qu'elles essaient désespérément d'apprendre l'anglais." },

    // --- TIME TRAVEL & PARADOXES ---
    { type: "SYSTEM", content: "Le voyage dans le temps est utilisé uniquement pour corriger les fautes de frappe historiques. Vous faites partie de la 'Grammar Police' temporelle." },
    { type: "SYSTEM", content: "Vous remontez le temps pour tuer Hitler, mais vous réalisez qu'il y a déjà une file d'attente de 200 autres voyageurs temporels devant sa porte." },
    { type: "SYSTEM", content: "Vous recevez une lettre de vous-même, écrite dans 50 ans, vous suppliant de ne surtout pas manger ce sandwich." },
    { type: "SYSTEM", content: "Le futur est déjà écrit. Le travail le plus important au monde est 'Effaceur de Destin' pour ceux qui n'aiment pas leur fin." },
    { type: "SYSTEM", content: "Vous voyagez 1000 ans dans le futur et découvrez que l'humanité vénère une vieille vidéo de chat comme une divinité sacrée." },

    // --- SUPER-HÉROS & VILAINS ---
    { type: "SYSTEM", content: "Le super-héros local est en fait le super-vilain. Il crée des catastrophes juste pour pouvoir les réparer et rester populaire." },
    { type: "SYSTEM", content: "Votre pouvoir est de devenir invisible, mais seulement si vous fermez les yeux. Vous courez souvent dans les murs." },
    { type: "SYSTEM", content: "Le super-vilain a gagné. Il a instauré la paix mondiale, l'éducation gratuite et la santé pour tous, juste pour faire chier le héros." },
    { type: "SYSTEM", content: "Vous êtes le comptable des super-héros. Vous devez leur expliquer qu'ils ne peuvent pas déduire la destruction d'un immeuble de leurs impôts." },

    // --- SECRETS DU MONDE ---
    { type: "SYSTEM", content: "Le sommeil n'est pas biologique. C'est le moment où le serveur de la réalité télécharge les données de la journée." },
    { type: "SYSTEM", content: "On découvre que les nuages sont les cerveaux de la Terre. Chaque orage est une crise de colère." },
    { type: "SYSTEM", content: "Les étoiles sont en fait les trous faits par les humains qui ont réussi à s'échapper de notre univers." },
    { type: "SYSTEM", content: "Vous trouvez une porte au fond de votre placard qui mène à la salle de contrôle de votre propre cerveau. Il n'y a personne aux commandes." },

    // --- PROMPTS COURTS & PERCUTANTS ---
    { type: "SYSTEM", content: "Le dernier mot jamais prononcé par l'humanité a été : 'Oups'." },
    { type: "SYSTEM", content: "Vous êtes né avec la connaissance de tout l'univers, mais vous perdez un fait chaque fois que vous apprenez le nom de quelqu'un." },
    { type: "SYSTEM", content: "La lune ne tourne pas. Elle nous fixe." },
    { type: "SYSTEM", content: "Vous trouvez un téléphone qui ne peut appeler que les morts. Vous composez votre propre numéro." },
    { type: "SYSTEM", content: "Le silence a une odeur. Vous venez de la sentir pour la première fois." },
    { type: "SYSTEM", content: "Les larmes sont la seule chose qui permet de voir la vérité. Le monde est magnifique quand on pleure." },
    { type: "SYSTEM", content: "Votre chat vient de vous demander : 'Est-ce qu'ils sont encore là ?' avant de se figer." },
    { type: "SYSTEM", content: "L'oxygène est un poison lent qui met 80 ans à nous tuer." },
    { type: "SYSTEM", content: "Vous trouvez une pièce de monnaie qui, quand on la lance, change le passé." },
    { type: "SYSTEM", content: "Le Père Noël n'apporte pas de cadeaux, il vient récupérer ceux que vous ne méritez plus." },
    { type: "SYSTEM", content: "Vous êtes une idée qui essaie de convaincre un auteur de l'écrire." },
    { type: "SYSTEM", content: "Le monde s'arrête de tourner. Littéralement. Tout le monde est projeté vers l'est à 1600 km/h." },
    { type: "SYSTEM", content: "Les miroirs retardent le reflet de 0,1 seconde. Aujourd'hui, le vôtre a pris 5 secondes de retard." },
    { type: "SYSTEM", content: "Vous êtes le seul à savoir que nous sommes mercredi. Tout le monde est convaincu qu'on est dimanche." },
    { type: "SYSTEM", content: "Chaque fois que vous tuez une araignée, vous entendez un cri humain au loin." },
    { type: "SYSTEM", content: "Vous vous réveillez et découvrez que vous êtes devenu une police d'écriture." },
    { type: "SYSTEM", content: "La gravité dépend de votre humeur. Plus vous êtes triste, plus vous êtes lourd." },
    { type: "SYSTEM", content: "Vous trouvez une télécommande pour les gens. Vous appuyez sur 'Mute' sur votre patron." },
    { type: "SYSTEM", content: "Les ombres des morts sont les seules choses qui projettent de la lumière." },
    { type: "SYSTEM", content: "Vous êtes un détective privé spécialisé dans les crimes commis pendant le sommeil." },
    { type: "SYSTEM", content: "Chaque fois que vous écrivez, ce que vous écrivez devient vrai. Vous n'avez plus d'encre." },
    { type: "SYSTEM", content: "Vous découvrez que le langage est une barrière inventée pour nous empêcher de lire dans les pensées." },
    { type: "SYSTEM", content: "La fin du monde a eu lieu hier, mais personne n'a remarqué." },
    { type: "SYSTEM", content: "Vous êtes le seul humain capable de voir les couleurs dans un monde en noir et blanc." },
    { type: "SYSTEM", content: "Votre reflet vous demande de le laisser sortir." },
    { type: "SYSTEM", content: "Les oiseaux ne chantent pas, ils rapportent ce qu'ils ont vu." },
    { type: "SYSTEM", content: "Vous trouvez un bouton 'Undo' dans la vraie vie." },
    { type: "SYSTEM", content: "Le soleil ne se lève pas ce matin. Ni le suivant." },
    { type: "SYSTEM", content: "Vous êtes un avocat qui défend des monstres sous les lits." },
    { type: "SYSTEM", content: "Chaque fois que vous clignez des yeux, le monde change un petit peu." },
    { type: "SYSTEM", content: "Vous trouvez un billet de 50€ qui revient toujours dans votre poche." },
    { type: "SYSTEM", content: "Vous êtes le premier humain à avoir une conversation avec une baleine. Elle est très déçue par nous." },
    { type: "SYSTEM", content: "Votre nom disparaît de tous les documents officiels. Vous n'existez plus." },
    { type: "SYSTEM", content: "Les souvenirs sont contagieux." },
    { type: "SYSTEM", content: "Vous découvrez que vous êtes un personnage secondaire dans le rêve de quelqu'un d'autre." },
    { type: "SYSTEM", content: "La pluie tombe vers le haut." },
    { type: "SYSTEM", content: "Vous pouvez voir les fils qui relient les gens qui s'aiment." },
    { type: "SYSTEM", content: "Vous êtes un robot qui croit être un humain, entouré d'humains qui sont des robots." },
    { type: "SYSTEM", content: "Le dictionnaire change ses définitions tous les jours." },
    { type: "SYSTEM", content: "Vous trouvez une porte qui mène à hier." },
    { type: "SYSTEM", content: "Le vent murmure des coordonnées GPS." },
    { type: "SYSTEM", content: "Chaque fois que vous riez, quelqu'un guérit." },
    { type: "SYSTEM", content: "Vous êtes le gardien du phare qui guide les âmes vers l'autre monde." },
    { type: "SYSTEM", content: "La lune est un projecteur." },
    { type: "SYSTEM", content: "Vous pouvez goûter les mots." },
    { type: "SYSTEM", content: "Le temps s'achète au supermarché." },
    { type: "SYSTEM", content: "Vous découvrez que vous êtes votre propre grand-père." },
    { type: "SYSTEM", content: "Les statues bougent quand on ne les regarde pas. Vraiment." },
    { type: "SYSTEM", content: "Vous êtes le dernier traducteur d'une langue morte qui peut ressusciter les gens." },
    { type: "SYSTEM", content: "Le monde est un livre et vous venez de trouver le marque-page." },
    { type: "SYSTEM", content: "Vous vous réveillez avec une nouvelle compétence chaque jour, mais vous perdez celle de la veille." },
    { type: "SYSTEM", content: "Les fleurs crient quand on les coupe." },
    { type: "SYSTEM", content: "Vous êtes le seul à savoir que le monde va finir dans une heure." },
    { type: "SYSTEM", content: "Chaque fois que vous perdez quelque chose, cela réapparaît dans une boîte mystérieuse." },
    { type: "SYSTEM", content: "La mort est une porte, et vous avez les clés." },
    ];